name: robustRMAB
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates==2021.10.8
  - certifi==2021.10.8
  - libcxx==12.0.0
  - libffi==3.3
  - libgfortran5==9.3.0
  - llvm-openmp==12.0.1
  - mpi==1.0
  - mpi4py==3.1.2
  - mpich==3.4.2
  - ncurses==6.3
  - openssl==1.1.1l
  - pip==21.2.4
  - python==3.8.12
  - python_abi==3.8
  - readline==8.1
  - setuptools==58.0.4
  - sqlite==3.36.0
  - tk==8.6.11
  - wheel==0.37.0
  - xz==5.2.5
  - zlib==1.2.11
  - pip:
    - appnope==0.1.2
    - attrs==21.2.0
    - backcall==0.2.0
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - decorator==5.1.0
    - gym==0.21.0
    - iniconfig==1.1.1
    - ipython==7.29.0
    - jedi==0.18.0
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - nashpy==0.0.28
    - numpy==1.21.4
    - packaging==21.2
    - pandas==1.3.4
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pluggy==1.0.0
    - prompt-toolkit==3.0.22
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py==1.11.0
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scipy==1.7.2
    - six==1.16.0
    - toml==0.10.2
    - torch==1.10.0
    - tqdm==4.62.3
    - traitlets==5.1.1
    - typing-extensions==3.10.0.2
    - wcwidth==0.2.5

