runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app --timeout 36000

runtime_config:
 python_version: 3
beta_settings:
  cloud_sql_instances: mmitra:asia-south1:armman,mmitra:asia-south1:mmitra-predictions

manual_scaling:
 instances: 1

resources:
 cpu: 2
 memory_gb: 10
 disk_size_gb: 10
